### ISSUE TITLE
License badge looks broken

### ISSUE THREAD

**Issue by spences10** [spences10/twitter-bot-bootstrap#11]

**Comment by spences10** [comment]
Seems ok now, must have been my mobile connection

**Comment by Raindeer44** [comment]
So now the first badge is having issues for me. It correlates to me accessing Github through a VPN, which has ad-blocking capability built in. There's no problem at all when I turn off my VPN. I don't know if this is worth fixing though.

**Comment by spences10** [comment]
I thought it may have been something like that, when I logged it I was behind a corporate proxy :+1:
