### ISSUE TITLE
add support to ESLint for project

### ISSUE THREAD

**Issue by Yogendra0Sharma** [spences10/twitter-bot-bootstrap#123]
We have to add ESLint for this project in order to code quality and readability.

**Comment by spences10** [comment]
This is entry level and things like ESLint cause hours of wheel spinning for things that are largely irrelevant in the grand scheme of things.

I'd be happy to have Prettier used in the project which can do pretty much the same and not cause the user and stress hunting down why there should not be a space after their variable name 🙃 

I'd happily accept a PR incorporating something like this in the project @Yogendra0Sharma 

I have a gist for something similar [here](https://gist.github.com/spences10/6fa39a905fa38c65560366cc002a169b)

```json
"scripts": {
  "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js'"
},
"devDependencies": {
  "prettier": "^1.6.1"
},
  "pre-commit": ["format"]
```

It is untested in this project.

**Comment by Yogendra0Sharma** [comment]
@spences10 Agreed, Prettier is a good option for this project.
