### ISSUE TITLE
Add user blacklist

### ISSUE THREAD

**Issue by spences10** [spences10/twitter-bot-bootstrap#127]
Add a user blacklist to the Twitterbot bootstrap 🏴 

I have similar functionality in another bot where the blacklist is configured in a `.env` file and you can use a comma-separated list in the `.env` file, like so:

```
BLACKLIST_USERNAMES=_100DaysOfCode,heroes_bot
```

Then use something along the same lines as what is here:

```javascript
const addTweet = require('./dbAddTweet')
const checkTweet = require('./dbCheckTweet')

const retweet = require('../api/retweet')
const config = require('../config')

const handleRetweet = (event) => {
  const blacklist = config.twitterConfig.blacklist.split(',')
  // all teh debugs!!
  console.log('====================')
  console.log('BLACKLIST USERS: ', blacklist)
  console.log('EVENT USER NAME: ', event.user.screen_name)
  console.log('INDEX OF NAME IN BLACKLIST: ', blacklist.indexOf(event.user.screen_name))
  console.log('====================')
  if (
    event.lang != config.twitterConfig.language ||
    !event.in_reply_to_status_id ||
    blacklist.indexOf(event.screen_name) > -1
  ) {
    return
  } else {
    // console.log(JSON.stringify(event.lang))
    // console.log(JSON.stringify(event))
    checkTweet(event).then((data) => {
      let count = data.length
      if (!count >= 0) {
        addTweet(event)
        // retweet
        retweet(event)
      }
    })
  }
}
```

The code for this is located here: https://github.com/spences10/twitter-bot-twit/blob/ee6d1e4bef3e37af84c1eccec2a12337513e165a/src/helpers/dbHandleRetweet.js#L1-L33

Ideally, this would be checked before (re)tweeting so it should go somewhere like @nikkilr88's last commit, here: 9c9b83b09bb55f77660c868b7d52ae3bff31b20b

**Comment by danielfsousa** [comment]
I would like to take this one

**Comment by spences10** [comment]
Cool, you may want to split the blacklist into a comma separated line, like:

```
BLACKLIST_USERNAMES=_100DaysOfCode,heroes_bot
```

**Comment by spences10** [comment]
How are you getting on with this @danielfsousa?

**Comment by spences10** [comment]
Hey @danielfsousa looks like there's been nothing committed to your fork so I'll open this up for other people interested in doing this.

**Comment by danielfsousa** [comment]
That's ok @spences10. Sorry for not replying sooner

**Comment by spences10** [comment]
Up for grabs now @toxxn 👍

**Comment by toxxn** [comment]
@spences10 

I went ahead and tried to use the #100DaysOfCode Twitter Bot since it seemed like it had the blacklist feature implemented already, however I'm stuck lol, that version of the bot won't deploy and when I just "npm start", it loops but doesn't post.... Maybe ill try your blacklist here haha.

**Comment by spences10** [comment]
Hey, just seen this, I don't seem to get notified about these. I answered your question about why the [bot won't deploy] there, I hope you understand 🙃 let me know if you need anything clarifying.

So in its simplest form the blacklist is `if (blacklist.indexOf(event.screen_name) > -1)` where `blacklist` is the usernames added from the config.

Most of it is detailed in the original post, I'm on mobile now so can't be any more specific at this time.

[bot won't deploy]: https://github.com/freeCodeCamp/100DaysOfCode-twitter-bot/issues/128
