### ISSUE TITLE
Missing .env file

### ISSUE THREAD

**Issue by EniaTitova** [spences10/twitter-bot-bootstrap#168]
Hi there, 

This is the first bit of code I've touched in my entire life so please be gentle, and apologies in advance if this is dumb/answered somewhere else.  

I can't seem to find the .env file to input my twitter credentials for the life of me.  Yes, I showed "hidden files" and even tried searching for it using the Navigation tab.  

Help? 

Thank you thank you thank you in advance.

**Comment by Raindeer44** [comment]
Welcome to GitHub! We're happy to have you!

The `.env` file is deliberately missing because it's designed to hold information specific to you. You need to create the file yourself, then continue following the instructions in `README.md`.

**Comment by spences10** [comment]
Thanks for taking the time to log an issue @EniaTitova and apologies if you have wasted some time trying to figure out what you should be doing. 

I tried to make it as clear as possible specifically for this sort of situation.

@Raindeer44 thank you for answering for me 😁 

So quick help is create the file like @Raindeer44 says, if you're in c9 then add the file in the file view to the root of the project. The file structure should look like this:

```text
my-app/
├─ images/
├─ src/
├─ .env
├─ .gitignore
 ....
```

@Raindeer44 is right, the `.env` file was in the project originally but people were adding their API keys to GitHub so I thought it best to remove it.

I'll leave this open for now for someone to pick up the changes, maybe you could contribute after you have your bot up and running @EniaTitova 😄

**Comment by EniaTitova** [comment]
Thanks @Raindeer44 and @spences10!  I'll be back at it next opportunity I get

**Comment by spences10** [comment]
Add in `.env-sample` like @cschweda has done here and update the `README.md`

https://github.com/cschweda/incognitabot/blob/master/.env-sample
