### ISSUE TITLE
Remove sentiment API key

### ISSUE THREAD

**Issue by spences10** [spences10/twitter-bot-bootstrap#17]
Direct users on how to get their own API key

**Comment by stevehemingway** [comment]
Just a clue would be nice!

**Comment by spences10** [comment]
Hey @stevehemingway, thanks for prompting me on this

I did add this to the README

---
Now you'll need to add your Twitter keys to the .env file. Just input the keys in their corresponding fields and save the file.

The SENTIMENT_KEY you can get a new API key at [https://market.mashape.com/vivekn/sentiment-3](https://market.mashape.com/vivekn/sentiment-3) your key is in the REQUEST EXAMPLE

```
CONSUMER_KEY=Fw***********P9
CONSUMER_SECRET=TD************Cq
ACCESS_TOKEN=31**************UC
ACCESS_TOKEN_SECRET=r0************S2
SENTIMENT_KEY=Gj************lF
```

Then you can then add some keywords into the strings.js file for what you want to search for as well as sub-queries.

---


Is that not clear enough?

I mean the only other thing I could think of was adding a picture :+1:

**Comment by spences10** [comment]
Resolved with #22

**Comment by stevehemingway** [comment]
Sorry, yes, it is obvious now you mention it!

**Comment by spences10** [comment]
I've added a gif detailing the process now as well, thanks again for the nudge :smile:
