### ISSUE TITLE
Crash during Retweet

### ISSUE THREAD

**Issue by andrewjburnett** [spences10/twitter-bot-bootstrap#196]
```sh
/Users/developer/Projects/bots/twitter/twitter-bot-bootstrap/src/helpers/isReply.js:5
    RT.test(tweet.text) ||
                  ^

TypeError: Cannot read property 'text' of undefined
    at isReply (/Users/developer/Projects/bots/twitter/twitter-bot-bootstrap/src/helpers/isReply.js:5:19)
    at bot.get (/Users/developer/Projects/bots/twitter/twitter-bot-bootstrap/src/api/retweet.js:31:14)
    at /Users/developer/Projects/bots/twitter/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:125:13
    at onRequestComplete (/Users/developer/Projects/bots/twitter/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:336:5)
    at Request.<anonymous> (/Users/developer/Projects/bots/twitter/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:348:7)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/Users/developer/Projects/bots/twitter/twitter-bot-bootstrap/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by spences10** [comment]
Hi @andrewjburnett thanks for using the Twitter bot bootstrap :👍

As a general guide when giving feedback on issues with open source projects it's usually helpful to give a bit more information with the console output to help maintainers understand where the problem may be.

As a user should have a look at previous issues to see if their issue has already been addressed.

I'm not able to help with this issue in its current state, please could you add some more detail so I can get a better idea of what is going on?

Many thanks 👍

**Comment by andrewjburnett** [comment]
Sure, what else can I provide?

I'm simply running the script with the following params:

QUERY_STRING=from:@nasa,from:@spacex,from:@StationCDRKelly,from:@googleresearch,from:@NASAJPL,from:@NASA_Hubble,from:@MarsCuriosity,from:@NASAKepler
RANDOM_REPLY=Hi @${screenName} thanks for the follow! What are you working on today?|@${screenName} thanks for following! What are you working on today?

RESULT_TYPE=mixed
TWITTER_LANG=en

TWITTER_RETWEET_RATE=30
TWITTER_SEARCH_COUNT=20

I've made no changes to isReply.js. What else can I provide to help get this sorted out?

**Comment by spences10** [comment]
🤔 

Not seen query string formed like that before, do you want to watch those accounts specifically and retweet anything from those accounts @andrewjburnett? 

If that's all you want then you could set up to watch the specific accounts and tweet with the `.on` api

There's some info on it here: https://github.com/spences10/twitter-bot-playground/blob/master/docs/05-use-twitter-stream-api.md

If you just want something to work then I'd suggest picking some search terms that will be tweeted by those accounts, the bootstrap only searches for keywords or phrases.

If you want the functionality to watch and retweet specific accounts then that functionality is outside the scope of this project.

Take a look at: https://github.com/spences10/delay-tweet which has some good examples of using the `.on` api but please note the project is unfinished so there may be some broken functionality, it was working pretty well for me when I was using it last. 

☝️ again though this wasn't watching specific accounts but specific keywords and phrases.

Thanks.

**Comment by andrewjburnett** [comment]
So the ```.on``` api is outside the scope of this project?

**Comment by spences10** [comment]
For following specific accounts and tweeting the statuses from those accounts with `.on` then yes 👍 

If you want to use that for watching for specific keyword/phrases then take a look at the previously linked `delay-tweet` repo 👌 

Have you tried changing the query to specific words and proses associated with the accounts you want to retweet from?
