### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by dumacdev** [spences10/twitter-bot-bootstrap#2]
Hi I get this output if i try to npm start your code.

/home/ubuntu/workspace/twitter-bot-bootstrap/src/bot.js:175
    var index = Math.floor(Math.random() * arr.length);
                                              ^

TypeError: Cannot read property 'length' of undefined

**Comment by spences10** [comment]
@dumacdev have you added search query criteria?

I have seen the error when there is no values in the `strings.js` module :+1:

**Comment by dumacdev** [comment]
module.exports = {
    queryString: [
        'javascript',
        'reactjs',
        'webdev'
    ],
    queryStringSubQuery: [
        '',
        '',
        ''
    ],
    resultType: [
        'mixed',
        'recent',
        'popular'
    ],
    responseString: [
        'Hi @screenName thanks for the follow! !CR',
        '@screenName thanks for following! !CR',
        'Hey @screenName thanks for the follow! !CR',
        'Thanks for following @screenName! !CR',
        'Hey @screenName, thanks for following! !CR',
        'Awesome @screenName, thanks for following! !CR',
        'Thanks for the follow @screenName! !CR',
        'Thanks for following @screenName! How are you today? !CR'
    ]
};

Do I need to fill out the queryStringSubQuery as well? What is that for?

Thanks for your response

**Comment by spences10** [comment]
Ok, first my apologies as I thought I only had the subquery stuff in the dev branch so there is no documentation just yet.

I have an empty string as one of my query strings and do not get that error :thinking: 

I added the sub queries so you can put in things like `' best practice`` and `' handy tip'` but I also have an empty one `''` 

Try adding some subquery strings see what happens

**Comment by dumacdev** [comment]
ok got it

instead of 

queryStringSubQuery: [
        '',
        '',
        ''
    ],

id did 

queryStringSubQuery: [
        ''
    ],

now it works just fine

Thanks for the help

**Comment by spences10** [comment]
It looks like I have update the README on the weekend, I really shouldn't drink alcohol and do GitHub :confused:
