### ISSUE TITLE
Twitter Suspends Account immediately

### ISSUE THREAD

**Issue by fussellm** [spences10/twitter-bot-bootstrap#210]
I went through the tutorial and it retweeted something during the "npm start", and again during the "npm run deploy", but as soon as i click the link to view the unique URL, it says on the Twitter website "account suspended".
I created a new twitter account tonight just to tinker with this stuff.
This is my first tweet/re-tweet.
It works during the testing phase.
I'm just doing a query search parameter of "pack9" -  which is the nickname of the NC State baseball team.

It is because i'm using such a new twitter account?   I'm really just trying to learn/tinker, but i guess they deem it malicious/fake?

Is this happening to anyone else?

**Comment by spences10** [comment]
Hey @fussellm thanks for taking an interest in the repo :+1: 

I'd say that your guess is probably correct here and it'll probably be something that should be added to the docs. 

Can you log into the Twitter account? Does it say anything when you log in?

**Comment by fussellm** [comment]
Yes. The twitter account is active from a browser/GUI standpoint.  But the link I get from the tutorial just says account suspended.   Thanks for the feedback.

**Comment by fussellm** [comment]
Interestingly, the bot is still kind of working?   It did a single re-tweet overnight, and when i just followed it from my main account, it replied "hi" twice.

**Comment by spences10** [comment]
:thinking: 

What unique URL is it? This from now?

Reopening as there needs to be something added to the docs around account suspension, if we can identify what's happened here other users can understand what's going on

**Comment by fussellm** [comment]
Hey.   i go to my "zeit" site and i click my unique URL
and it goes me a page 
Synced...
prepared container
installed and built project
started
then it says "Ready visit now" and here's the link
https://testtwitter9191-ygpqmiujzm.now.sh/

The twitter account is GlenDavis919

**Comment by fussellm** [comment]
i opened a new AWS environment and retyped the setup steps, just to have a fresh version.
the retweet worked in test and production
here's the new link https://twitter-bot-bootstrap-azffdittug.now.sh/

**Comment by fussellm** [comment]
Ok, i see on my phone its saying @ undefined when it says the account is suspended.
The latest version i made is currently working, retweeting the search terms every 20 minutes, so i guess i'm going to leave it alone, and then see what other things i can tinker with, or even do one of those  write-from-scratch tutorials to understand it more.

Thanks!

**Comment by spences10** [comment]
Closing this now due to inactivity, reopen if you have anything else to add

Many thanks
