### ISSUE TITLE
No repository field for twitter-bot@1.0.0

### ISSUE THREAD

**Issue by mahaase1** [spences10/twitter-bot-bootstrap#25]
On install, two exceptions -
npm WARN package.json twitter-bot@1.0.0 No repository field.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

I grabbed uuid and it's resolved but what's package alternative for the twitter-bot?
Looking forward to taking this on test drive. And great instructions!!

**Comment by spences10** [comment]
Hi @mahaase1 thanks for taking the time to log an issue, the warnings are just that :smile: warnings 

The code will work fine without the `repository` field in there so you can ignore the warnings or add in the repository if you like it's up to you this is a bootstrap so you can get started and do with the code what you please :+1: 

I'll add some documentation about warnings and ignoring them along with details on the hidden files.

Thanks closing this and referencing #26 for the documentation
