### ISSUE TITLE
Violating Twitter ToS

### ISSUE THREAD

**Issue by spences10** [spences10/twitter-bot-bootstrap#48]
:grimacing: uh oh!

https://support.twitter.com/articles/76915

![image](https://cloud.githubusercontent.com/assets/234708/26111112/22aa3d72-3a4c-11e7-921c-9ba4fc15324a.png)

Better take out the like functionality!

**Comment by ryan-mulrooney** [comment]
Indeed! The bot crashes after liking a tweet anyway, so 👍 .

**Comment by ryan-mulrooney** [comment]
It crashes when retweeting too, but less frequently. In both cases the crash is due to:

`var sentim = result.body.result.sentiment
TypeError: Cannot read property 'sentiment' of undefined`

This is usually undefined when receiving a 502 response after making the `httpCall.send('txt=' + favoriteText)` call.

**Comment by ryan-mulrooney** [comment]
Oh, sorry, ignore that - I'm incurring 502s when testing the endpoint in Mashape's own app...

**Comment by ashenwgt** [comment]
Here also it crashes when retweeting due to` var sentim = result.body.result.sentiment` line. Does anyone know how to fix it?

**Comment by spences10** [comment]
Hi @ashenwgt @ryan-mulrooney thanks for your input, this issue was relating to the Twitter terms of service not the Mashape Sentiment API

Closing this with reference to what was intended to fix the ToS issue 😉 

Also removed Semtiment in favour of using `filter: 'safe',` in the retweet function, this should get around bad language being retweeted, negative sentiment not though.

If either of you resolve your issue and feel it can be added back into the bootstrap I'm waiting for your PR 👌 

Thanks

**Comment by ashenwgt** [comment]
Thanks @spences10  for your quick workaround. Now the bot is working fine. It is now retweeting the news related to the floods happening in Sri Lanka these days: https://twitter.com/FloodSL_Bot

**Comment by spences10** [comment]
@ashenwgt I hope it serves you well! And that it helps :+1:

**Comment by spences10** [comment]
@ashenwgt if you need any help configuring it let me know if I can help :+1:
