### ISSUE TITLE
Error: Twit config must include `consumer_key` when using user auth. 

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [spences10/twitter-bot-bootstrap#76]
After setting up the configuration in the .env file and running npm start I get the above error.

**Comment by spences10** [comment]
Hey @GoodFaithParadigm8 

**Twit config must include `consumer_key` when using user auth** indicates there is an issue with how the config is set up, so are there any `""` or `''` around the API keys in the `.env` file?

closing this as it's a configuration issue and not an issue with the bot itself

I'll happily carry on the thread until you have it resolved though :+1:

**Comment by GoodFaithParadigm8** [comment]
Ended up building a bot using a different scheme. Love the 12 Factor App Methodology used in yours though. Knew raising an issue wasn't the best place to ask about the error I got but didn't think it would have gotten a response on Stack Exchange. I'll revisit the bot at a later time to see if I properly set up the configuration. Thanks!

**Comment by spences10** [comment]
for some reason I didn't get a notification for this issue and only noticed it when I logged in to log one myself 🙃

**Comment by mathias3** [comment]
i got this problem and have all keys sat up properly ( no spaces or  any "" or '' around the API keys)

**Comment by spences10** [comment]
You have your `.env` file set up like in the example @mathias3?

```sh
TWITTER_CONSUMER_KEY=kjfjsd8kjfjsd8kjfjsd8
TWITTER_CONSUMER_SECRET=kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8
TWITTER_ACCESS_TOKEN=kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8
TWITTER_ACCESS_TOKEN_SECRET=kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8kjfjsd8
```

**Comment by spences10** [comment]
And you have the rest of your query information set up??

```sh
QUERY_STRING=my super awesome query string!,google,android

RANDOM_REPLY=Hi @${screenName} thanks for the follow! What are you working on today?|@${screenName} thanks for following! What are you working on today?

RESULT_TYPE=mixed
TWITTER_LANG=en

TWITTER_RETWEET_RATE=.1
TWITTER_SEARCH_COUNT=20
```

**Comment by mathias3** [comment]
Exactly:

 TWITTER_CONSUMER_KEY=xYs05WxxxxxxxxxxxnEHRa
TWITTER_CONSUMER_SECRET=hiHikxaINsVbWxxxxxxxxxe844EvNHDAWqH
TWITTER_ACCESS_TOKEN=9588xxxxxxx9297-Gd8tZKnkiqyxxxxxxxNUXsYeUsPyYT
TWITTER_ACCESS_TOKEN_SECRET=xZ4e3y6MFnQxxxxxxxxxxxxxxxqBAf99nufq6hkOr5

QUERY_STRING=my super awesome query string!,google,android

RANDOM_REPLY=Hi @${screenName} thanks for the follow! What are you working on today?|@${screenName} thanks for following! What are you working on today?

RESULT_TYPE=mixed
TWITTER_LANG=en

TWITTER_RETWEET_RATE=.1
TWITTER_SEARCH_COUNT=20
