### ISSUE TITLE
Filter out replies?

### ISSUE THREAD

**Issue by nocean** [spences10/twitter-bot-bootstrap#80]
First off, thank you for your very detailed guide on setting this up.

I know we can use the query syntax 'from:@username' to retweet tweets from a specific Twitter account, however is there a way to filter those tweets to not retweet replies?

**Comment by spences10** [comment]
Hi @nocean thanks for logging this and yes there is I actually need to get that in here, I have it in one of my other repos currently, here:

```javascript
const Twit = require('twit')
const config = require('../config')

const bot = new Twit(config.twitterKeys)

const retweet = (event) => {
  // console.log(JSON.stringify(event.lang))
  // console.log(JSON.stringify(event))
  // event.source.screen_name
  if (event.lang != config.twitterConfig.language) return
  console.log('====================')
  console.log(event.text)
  console.log('====================')
  // don't retweet replies
  if (!event.in_reply_to_status_id) {
    bot.post('statuses/retweet/:id', { id: event.id_str }, (err, res) => {
      if (err) {
        console.log('RETWEET ERRORDERP: ', err.message)
      }
      console.log('RT SUCCESS: ', event.text)
    })
  }
}

module.exports = retweet
```

Basically the bit you want is `if (!event.in_reply_to_status_id)` so you could have it as a stop block like I have for the language further up: ` if (event.lang != config.twitterConfig.language) return` just return out of the function 👍 

That make sense?

**Comment by nocean** [comment]
Thanks a lot for the quick reply. This looks perfect. Will give it a go!
