### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by spences10** [spences10/twitter-bot-bootstrap#88]
`config.js` key values pairs need to reflect what is in the `.env` file

Refer to https://github.com/spences10/twitter-bot-bootstrap/issues/87 for details on how to resolve

**Comment by pabrams** [comment]
I noticed that the RANDOM_REPLY string is actually pipe-separated, but I believe the documentation says it is comma-separated.

**Comment by spences10** [comment]
Yeah, I use pipes so that a response can then use a comma, like: "hey @{userName}, how's things?"
